---
name: Scrape
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 0 */1 * * *  # hver time
jobs:
  scheduled:
    runs-on: ubuntu-latest
    environment: scrape
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.42.x
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Run script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: deno task scrape
      - name: commit it
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
